Add NRPE checks for services
openstack-charmers/charm-layer-ovn pull request #23
Opened 2020-09-28 04:58 UTC by xavpaice

Adds the nrpe-external-master layer and checks for services managed by
this charm.

func-test-pr: https://github.com/openstack-charmers/zaza-openstack-tests/pull/433

Closes-Bug: #1896674

2020-09-30 07:40 UTC, fnordahl requested changes
Thank you for your work on this, it looks pretty great and I have a couple of comments in-line

2020-09-30 07:40 UTC, fnordahl commented on lib/charms/ovn_charm.py
> +            self.nrpe_check_services.append(self.metadata_agent)
The charm class `__init__` method already makes choices based on OpenStack being present or not, could we do this there instead?

2020-09-30 07:40 UTC, fnordahl commented on lib/charms/ovn_charm.py
> +            self.metadata_agent = 'networking-ovn-metadata-agent'
If you move the definition of `self.nrpe_check_services` above this block you can append the metadata agent to it when OpenStack is enabled. Then you don't need to expose the `metadata_agent` variable as a class instance variable.

2020-09-30 07:40 UTC, fnordahl commented on lib/charms/ovn_charm.py
> +    metadata_agent = 'neutron-ovn-metadata-agent'
See previous comment about handling this in the per-release class `__init__` method which would make this redundant.

2020-09-30 22:00 UTC, xavpaice commented
Thanks for that feedback - I've updated with a fresh commit for some updates and improved the unit test for nrpe as a result.

2020-10-01 06:15 UTC, fnordahl approved these changes
LGTM, thanks!

2020-10-01 06:15 UTC, merged